###
GET http://localhost:3000/album HTTP/1.1
###
GET http://localhost:3000/album/1 HTTP/1.1
###
# GET http://example/topics/1 HTTP/1.1
###
POST http://localhost:3000/album HTTP/1.1
content-type: application/json

{
  "name": "album info",
  "description": "Some album desc",
  "isPublished": false
}



###
GET http://localhost:3000/users HTTP/1.1
###
GET http://localhost:3000/users/1 HTTP/1.1
###
# GET http://example/topics/1 HTTP/1.1
###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "Nick",
  "lastName": "Tref",
  "isActive": false
}